// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: server/serverpb/api.proto

package serverpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Patient message
type Patient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Prescriptions []*Prescription        `protobuf:"bytes,8,rep,name=prescriptions,proto3" json:"prescriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Patient) Reset() {
	*x = Patient{}
	mi := &file_server_serverpb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient) ProtoMessage() {}

func (x *Patient) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient.ProtoReflect.Descriptor instead.
func (*Patient) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{0}
}

func (x *Patient) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Patient) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Patient) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Patient) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Patient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Patient) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Patient) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Patient) GetPrescriptions() []*Prescription {
	if x != nil {
		return x.Prescriptions
	}
	return nil
}

// Prescription message
type Prescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Medication    string                 `protobuf:"bytes,2,opt,name=medication,proto3" json:"medication,omitempty"`
	Dosage        string                 `protobuf:"bytes,3,opt,name=dosage,proto3" json:"dosage,omitempty"`
	Frequency     string                 `protobuf:"bytes,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Notes         string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prescription) Reset() {
	*x = Prescription{}
	mi := &file_server_serverpb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prescription) ProtoMessage() {}

func (x *Prescription) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prescription.ProtoReflect.Descriptor instead.
func (*Prescription) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{1}
}

func (x *Prescription) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Prescription) GetMedication() string {
	if x != nil {
		return x.Medication
	}
	return ""
}

func (x *Prescription) GetDosage() string {
	if x != nil {
		return x.Dosage
	}
	return ""
}

func (x *Prescription) GetFrequency() string {
	if x != nil {
		return x.Frequency
	}
	return ""
}

func (x *Prescription) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Prescription) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// --- Patient RPC messages ---
type CreatePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePatientRequest) Reset() {
	*x = CreatePatientRequest{}
	mi := &file_server_serverpb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePatientRequest) ProtoMessage() {}

func (x *CreatePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePatientRequest.ProtoReflect.Descriptor instead.
func (*CreatePatientRequest) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePatientRequest) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

type CreatePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePatientResponse) Reset() {
	*x = CreatePatientResponse{}
	mi := &file_server_serverpb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePatientResponse) ProtoMessage() {}

func (x *CreatePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePatientResponse.ProtoReflect.Descriptor instead.
func (*CreatePatientResponse) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

type GetPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientRequest) Reset() {
	*x = GetPatientRequest{}
	mi := &file_server_serverpb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientRequest) ProtoMessage() {}

func (x *GetPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientRequest.ProtoReflect.Descriptor instead.
func (*GetPatientRequest) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetPatientRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientResponse) Reset() {
	*x = GetPatientResponse{}
	mi := &file_server_serverpb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientResponse) ProtoMessage() {}

func (x *GetPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientResponse.ProtoReflect.Descriptor instead.
func (*GetPatientResponse) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetPatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

type ListPatientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientsRequest) Reset() {
	*x = ListPatientsRequest{}
	mi := &file_server_serverpb_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientsRequest) ProtoMessage() {}

func (x *ListPatientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientsRequest.ProtoReflect.Descriptor instead.
func (*ListPatientsRequest) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListPatientsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPatientsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListPatientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*Patient             `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientsResponse) Reset() {
	*x = ListPatientsResponse{}
	mi := &file_server_serverpb_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientsResponse) ProtoMessage() {}

func (x *ListPatientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientsResponse.ProtoReflect.Descriptor instead.
func (*ListPatientsResponse) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{7}
}

func (x *ListPatientsResponse) GetPatients() []*Patient {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *ListPatientsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- Prescription RPC messages ---
type CreatePrescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     uint64                 `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Prescription  *Prescription          `protobuf:"bytes,2,opt,name=prescription,proto3" json:"prescription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrescriptionRequest) Reset() {
	*x = CreatePrescriptionRequest{}
	mi := &file_server_serverpb_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrescriptionRequest) ProtoMessage() {}

func (x *CreatePrescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrescriptionRequest.ProtoReflect.Descriptor instead.
func (*CreatePrescriptionRequest) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePrescriptionRequest) GetPatientId() uint64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *CreatePrescriptionRequest) GetPrescription() *Prescription {
	if x != nil {
		return x.Prescription
	}
	return nil
}

type CreatePrescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prescription  *Prescription          `protobuf:"bytes,1,opt,name=prescription,proto3" json:"prescription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrescriptionResponse) Reset() {
	*x = CreatePrescriptionResponse{}
	mi := &file_server_serverpb_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrescriptionResponse) ProtoMessage() {}

func (x *CreatePrescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrescriptionResponse.ProtoReflect.Descriptor instead.
func (*CreatePrescriptionResponse) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePrescriptionResponse) GetPrescription() *Prescription {
	if x != nil {
		return x.Prescription
	}
	return nil
}

type GetPrescriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrescriptionRequest) Reset() {
	*x = GetPrescriptionRequest{}
	mi := &file_server_serverpb_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrescriptionRequest) ProtoMessage() {}

func (x *GetPrescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrescriptionRequest.ProtoReflect.Descriptor instead.
func (*GetPrescriptionRequest) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetPrescriptionRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPrescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prescription  *Prescription          `protobuf:"bytes,1,opt,name=prescription,proto3" json:"prescription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrescriptionResponse) Reset() {
	*x = GetPrescriptionResponse{}
	mi := &file_server_serverpb_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrescriptionResponse) ProtoMessage() {}

func (x *GetPrescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrescriptionResponse.ProtoReflect.Descriptor instead.
func (*GetPrescriptionResponse) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetPrescriptionResponse) GetPrescription() *Prescription {
	if x != nil {
		return x.Prescription
	}
	return nil
}

type ListPrescriptionsForPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     uint64                 `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrescriptionsForPatientRequest) Reset() {
	*x = ListPrescriptionsForPatientRequest{}
	mi := &file_server_serverpb_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrescriptionsForPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrescriptionsForPatientRequest) ProtoMessage() {}

func (x *ListPrescriptionsForPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrescriptionsForPatientRequest.ProtoReflect.Descriptor instead.
func (*ListPrescriptionsForPatientRequest) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{12}
}

func (x *ListPrescriptionsForPatientRequest) GetPatientId() uint64 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

type ListPrescriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prescriptions []*Prescription        `protobuf:"bytes,1,rep,name=prescriptions,proto3" json:"prescriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrescriptionsResponse) Reset() {
	*x = ListPrescriptionsResponse{}
	mi := &file_server_serverpb_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrescriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrescriptionsResponse) ProtoMessage() {}

func (x *ListPrescriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_serverpb_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrescriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListPrescriptionsResponse) Descriptor() ([]byte, []int) {
	return file_server_serverpb_api_proto_rawDescGZIP(), []int{13}
}

func (x *ListPrescriptionsResponse) GetPrescriptions() []*Prescription {
	if x != nil {
		return x.Prescriptions
	}
	return nil
}

var File_server_serverpb_api_proto protoreflect.FileDescriptor

const file_server_serverpb_api_proto_rawDesc = "" +
	"\n" +
	"\x19server/serverpb/api.proto\x12\bserverpb\"\xf1\x01\n" +
	"\aPatient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12<\n" +
	"\rprescriptions\x18\b \x03(\v2\x16.serverpb.PrescriptionR\rprescriptions\"\xa6\x01\n" +
	"\fPrescription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1e\n" +
	"\n" +
	"medication\x18\x02 \x01(\tR\n" +
	"medication\x12\x16\n" +
	"\x06dosage\x18\x03 \x01(\tR\x06dosage\x12\x1c\n" +
	"\tfrequency\x18\x04 \x01(\tR\tfrequency\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\"C\n" +
	"\x14CreatePatientRequest\x12+\n" +
	"\apatient\x18\x01 \x01(\v2\x11.serverpb.PatientR\apatient\"D\n" +
	"\x15CreatePatientResponse\x12+\n" +
	"\apatient\x18\x01 \x01(\v2\x11.serverpb.PatientR\apatient\"#\n" +
	"\x11GetPatientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"A\n" +
	"\x12GetPatientResponse\x12+\n" +
	"\apatient\x18\x01 \x01(\v2\x11.serverpb.PatientR\apatient\"C\n" +
	"\x13ListPatientsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"[\n" +
	"\x14ListPatientsResponse\x12-\n" +
	"\bpatients\x18\x01 \x03(\v2\x11.serverpb.PatientR\bpatients\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"v\n" +
	"\x19CreatePrescriptionRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x04R\tpatientId\x12:\n" +
	"\fprescription\x18\x02 \x01(\v2\x16.serverpb.PrescriptionR\fprescription\"X\n" +
	"\x1aCreatePrescriptionResponse\x12:\n" +
	"\fprescription\x18\x01 \x01(\v2\x16.serverpb.PrescriptionR\fprescription\"(\n" +
	"\x16GetPrescriptionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"U\n" +
	"\x17GetPrescriptionResponse\x12:\n" +
	"\fprescription\x18\x01 \x01(\v2\x16.serverpb.PrescriptionR\fprescription\"C\n" +
	"\"ListPrescriptionsForPatientRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\x04R\tpatientId\"Y\n" +
	"\x19ListPrescriptionsResponse\x12<\n" +
	"\rprescriptions\x18\x01 \x03(\v2\x16.serverpb.PrescriptionR\rprescriptions2\x9a\x04\n" +
	"\x03Api\x12P\n" +
	"\rCreatePatient\x12\x1e.serverpb.CreatePatientRequest\x1a\x1f.serverpb.CreatePatientResponse\x12G\n" +
	"\n" +
	"GetPatient\x12\x1b.serverpb.GetPatientRequest\x1a\x1c.serverpb.GetPatientResponse\x12M\n" +
	"\fListPatients\x12\x1d.serverpb.ListPatientsRequest\x1a\x1e.serverpb.ListPatientsResponse\x12_\n" +
	"\x12CreatePrescription\x12#.serverpb.CreatePrescriptionRequest\x1a$.serverpb.CreatePrescriptionResponse\x12V\n" +
	"\x0fGetPrescription\x12 .serverpb.GetPrescriptionRequest\x1a!.serverpb.GetPrescriptionResponse\x12p\n" +
	"\x1bListPrescriptionsForPatient\x12,.serverpb.ListPrescriptionsForPatientRequest\x1a#.serverpb.ListPrescriptionsResponseB=Z;github.com/hcliff-zhang/playground/server/serverpb;serverpbb\x06proto3"

var (
	file_server_serverpb_api_proto_rawDescOnce sync.Once
	file_server_serverpb_api_proto_rawDescData []byte
)

func file_server_serverpb_api_proto_rawDescGZIP() []byte {
	file_server_serverpb_api_proto_rawDescOnce.Do(func() {
		file_server_serverpb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_serverpb_api_proto_rawDesc), len(file_server_serverpb_api_proto_rawDesc)))
	})
	return file_server_serverpb_api_proto_rawDescData
}

var file_server_serverpb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_server_serverpb_api_proto_goTypes = []any{
	(*Patient)(nil),                            // 0: serverpb.Patient
	(*Prescription)(nil),                       // 1: serverpb.Prescription
	(*CreatePatientRequest)(nil),               // 2: serverpb.CreatePatientRequest
	(*CreatePatientResponse)(nil),              // 3: serverpb.CreatePatientResponse
	(*GetPatientRequest)(nil),                  // 4: serverpb.GetPatientRequest
	(*GetPatientResponse)(nil),                 // 5: serverpb.GetPatientResponse
	(*ListPatientsRequest)(nil),                // 6: serverpb.ListPatientsRequest
	(*ListPatientsResponse)(nil),               // 7: serverpb.ListPatientsResponse
	(*CreatePrescriptionRequest)(nil),          // 8: serverpb.CreatePrescriptionRequest
	(*CreatePrescriptionResponse)(nil),         // 9: serverpb.CreatePrescriptionResponse
	(*GetPrescriptionRequest)(nil),             // 10: serverpb.GetPrescriptionRequest
	(*GetPrescriptionResponse)(nil),            // 11: serverpb.GetPrescriptionResponse
	(*ListPrescriptionsForPatientRequest)(nil), // 12: serverpb.ListPrescriptionsForPatientRequest
	(*ListPrescriptionsResponse)(nil),          // 13: serverpb.ListPrescriptionsResponse
}
var file_server_serverpb_api_proto_depIdxs = []int32{
	1,  // 0: serverpb.Patient.prescriptions:type_name -> serverpb.Prescription
	0,  // 1: serverpb.CreatePatientRequest.patient:type_name -> serverpb.Patient
	0,  // 2: serverpb.CreatePatientResponse.patient:type_name -> serverpb.Patient
	0,  // 3: serverpb.GetPatientResponse.patient:type_name -> serverpb.Patient
	0,  // 4: serverpb.ListPatientsResponse.patients:type_name -> serverpb.Patient
	1,  // 5: serverpb.CreatePrescriptionRequest.prescription:type_name -> serverpb.Prescription
	1,  // 6: serverpb.CreatePrescriptionResponse.prescription:type_name -> serverpb.Prescription
	1,  // 7: serverpb.GetPrescriptionResponse.prescription:type_name -> serverpb.Prescription
	1,  // 8: serverpb.ListPrescriptionsResponse.prescriptions:type_name -> serverpb.Prescription
	2,  // 9: serverpb.Api.CreatePatient:input_type -> serverpb.CreatePatientRequest
	4,  // 10: serverpb.Api.GetPatient:input_type -> serverpb.GetPatientRequest
	6,  // 11: serverpb.Api.ListPatients:input_type -> serverpb.ListPatientsRequest
	8,  // 12: serverpb.Api.CreatePrescription:input_type -> serverpb.CreatePrescriptionRequest
	10, // 13: serverpb.Api.GetPrescription:input_type -> serverpb.GetPrescriptionRequest
	12, // 14: serverpb.Api.ListPrescriptionsForPatient:input_type -> serverpb.ListPrescriptionsForPatientRequest
	3,  // 15: serverpb.Api.CreatePatient:output_type -> serverpb.CreatePatientResponse
	5,  // 16: serverpb.Api.GetPatient:output_type -> serverpb.GetPatientResponse
	7,  // 17: serverpb.Api.ListPatients:output_type -> serverpb.ListPatientsResponse
	9,  // 18: serverpb.Api.CreatePrescription:output_type -> serverpb.CreatePrescriptionResponse
	11, // 19: serverpb.Api.GetPrescription:output_type -> serverpb.GetPrescriptionResponse
	13, // 20: serverpb.Api.ListPrescriptionsForPatient:output_type -> serverpb.ListPrescriptionsResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_server_serverpb_api_proto_init() }
func file_server_serverpb_api_proto_init() {
	if File_server_serverpb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_serverpb_api_proto_rawDesc), len(file_server_serverpb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_serverpb_api_proto_goTypes,
		DependencyIndexes: file_server_serverpb_api_proto_depIdxs,
		MessageInfos:      file_server_serverpb_api_proto_msgTypes,
	}.Build()
	File_server_serverpb_api_proto = out.File
	file_server_serverpb_api_proto_goTypes = nil
	file_server_serverpb_api_proto_depIdxs = nil
}
